### ISSUE TITLE
Hi, I cannot reproduce the result.

### ISSUE THREAD

**Issue by aachenhang** [irfanICMLL/structure_knowledge_distillation#22] opened 2020-03-05 08:42 UTC
Hi，I have used your code and failed to reproduce the result. Here are my results.

I used the master branch.
When load the imagenet weight, I skip 'conv1.weight' and 'layer1.0.conv1.weight' cause their shape is different with the official Resnet18.
The results are all best IOU on the cityscape eval set during training.
- Baseline:  0.619
- Baseline + PI: 0.397
- Baseline + PI + PA: 0.414
- Baseline + PI + PA + HO: D_loss NAN 

Could you send me your log?

**Comment by aachenhang** [comment] 2020-03-05 08:46
By the way, I found that training more iteration on the baseline can make the result better.

- Baseline: 0.619
- + Resume the 0.619 ckpt and train more 40k iters without any distillation: 0.676
- + Resume  the 0.676 ckpt and train more 40k iters without any distillation: 0.700

**Comment by irfanICMLL** [comment] 2020-03-05 12:31
I have already sent the training log to you through the email.

**Comment by irfanICMLL** [comment] 2020-03-05 12:58
I will close the issue. If you have further questions, please feel free to contact me.

**Closed as completed** 2020-03-05 12:58 UTC

**Comment by Jankyee** [comment] 2020-03-19 05:40
Actually, I came across the same problems and get the similar results as @aachenhang .....

Have you fixed it?

**Comment by DanceInDark** [comment] 2020-07-18 02:11
> Hi，I have used your code and failed to reproduce the result. Here are my results.
> 
> I used the master branch.
> When load the imagenet weight, I skip 'conv1.weight' and 'layer1.0.conv1.weight' cause their shape is different with the official Resnet18.
> The results are all best IOU on the cityscape eval set during training.
> 
> * Baseline:  0.619
> * Baseline + PI: 0.397
> * Baseline + PI + PA: 0.414
> * Baseline + PI + PA + HO: D_loss NAN
> 
> Could you send me your log?

I also have the same problem and cannot reproduce the result. Have you fixed this?
